services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eventhub-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=EventHub2026
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    container_name: eventhub-seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"

  api:
    build:
      context: .
      dockerfile: EventHub.API/Dockerfile
    container_name: eventhub-api
    depends_on:
      - db
      - seq
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=EventHubDb;User Id=sa;Password=EventHub2026;TrustServerCertificate=True;

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventhub-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  sqlserverdata: