server {
    listen 5173;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Ovo je ključno za React rutiranje (da ne dobijaš 404 na osvežavanju)
        try_files $uri $uri/ /index.html;
    }
}